type Todo {
    id: ID!
    title: String!
    completed: Boolean!
}

type Query {
    getTodos: [Todo]
}

type Mutation {
    addTodo(title: String!): Todo
    delTodo(id: ID!): Todo
    updateTodo(title: String!, id: ID!, completed: Boolean!): Todo
}